# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    # activate different ways to authenticate

    # http_basic: ~
    # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

    # form_login: ~
    # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
#            anonymous: ~
#            form_login:
#                login_path: /login
#                check_path: /login_check

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
